version: '2'

services:
  mongo:
    image: mongo:3.4.2
    ports: [ '27017:27017' ]
    volumes:
      - 'mongo-data:/data/db'
      - 'mongo-config:/data/configdb'
  redis:
    image: redis:4.0.1-alpine
    ports: [ '6379:6379' ]
    volumes:
      - 'redis-data:/data'

volumes:
  mongo-data:
  mongo-config:
  redis-data:
