server:
  port: 8080
zuul:
  routes:
    order:
      path: /orders/**
      service-id: order
      strip-prefix: false
    catalog:
      path: /items/**
      service-id: catalog
      strip-prefix: false
    notification:
      service-id: notification             
spring:
  application:
    name: edge
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka} 